# Cloudflare Pages 配置文件

# 构建命令
[build]
  command = "npm run docs:build"
  publish = "docs/.vitepress/dist"
  
# 环境变量
[build.environment]
  NODE_VERSION = "18"

# 路由配置
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Country = ["*"]}

# 自定义头部
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
